blank_issues_enabled: false
contact_links:
  - name:  腾讯问卷申请渠道
    url: https://wj.qq.com/s2/25766356/765a/
    about: 如果你不习惯使用 GitHub，可以通过腾讯问卷提交申请。
  - name: 阅读加入指南
    url: https://docs.taten.org/join-us.html
    about: 在申请前，建议先阅读我们的团队规范。
